### ISSUE TITLE
Add install instructions to README?

### ISSUE THREAD

**Issue by VincentWo** [Canop/bacon#126]
Hi, I love the project :)

But at the moment there aren't any install instructions, which might be confusing especially for beginners.

My suggestion would be to add:

## Installation
```
cargo install --locked bacon
```
directly beneath #Documentation,

Can of course also open a pull requests, just wanted to check beforehand

**Comment by Canop** [comment]
The idea was to make the readme just an overview, in order to avoid the risk of having people miss the [complete guide](https://dystroy.org/bacon/).

If we add installation instructions directly in the readme, there must be a  link below directing newcomers to the site for configuration and efficient usage of bacon.

**Comment by joshka** [comment]
Incidentally as a rust n00b, I've often wondered why the --locked is necessary when installing apps like this. My path to reading the cargo book led me to understand what the flag does, but not why it's necessary. Perhaps it would be worth putting a quick note about how it "Ensures that the command is run with exactly the dependencies specified in the lock file rather than automatically using later dependencies to <reduce support burden?>", or something like that?
