### ISSUE TITLE
Inconsistent stdout flushing when using `bacon run`

### ISSUE THREAD

**Issue by jasondyoungberg** [Canop/bacon#185]
When executing a Rust program using the `bacon run` command for the first time, the standard output is flushed on every newline. However, on subsequent runs, flushing appears to occur only upon program termination rather than as expected — every time the program itself issues a flush.

## Expected Behavior

The expectation is for `bacon run` to flush the output consistently, in alignment with the behavior of my Rust program, which flushes after each output operation.

## Current Behavior

- **Initial `bacon run` execution**: Output is flushed on every newline.
- **Subsequent `bacon run` executions**: Output is flushed only upon program termination.

## Steps to Reproduce

1. Use the following Rust code snippet:

    ```rust
    use std::{
        io::{stdout, Write},
        thread::sleep,
        time::Duration,
    };

    fn main() {
        for i in 0..10 {
            print!("\n{i}: ");
            for j in 0..10 {
                print!("{j} ");
                stdout().flush().unwrap();
                sleep(Duration::from_millis(100));
            }
        }
    }
    ```

2. Run the program using `cargo run` to observe the expected behavior where every number is printed sequentially.
3. Execute the program using `bacon run` to note the difference: only every line is printed during execution.
4. On automatic execution upon save, observe that the output is displayed wholly at the end.

## Environment

- Rust version: 1.77.1
- bacon version: 2.16.0
- Operating System: Windows 11

**Comment by Canop** [comment]
Two phenomenons here:

1) bacon works by line.

2) on the first run of a task, because there's no report to display, bacon just displays the command output as it comes. On subsequent runs, bacon waits for the complete output before analyzing it then replacing its display. This is by design.

The fact bacon works by line is unlikely to change.

If you want to see, on a `run` execution, the raw output as it comes, you may bind a key to `toggle-raw-output` and trigger it.

If you always want, for a `run` job, to see the output while the execution is in progress, you may add this to the job configuration:
`background = false
`
