### ISSUE TITLE
Run rocket: Emojis and some colored text not rendering

### ISSUE THREAD

**Issue by ScratchX98** [Canop/bacon#89]
![image](https://user-images.githubusercontent.com/76647797/192232125-882d7d7f-5545-4e83-812f-ee69cb7ef117.png)
Left: Bacon, Right: Cargo watch

Using rocket framework and last version of bacon from cargo,.

**Comment by Stargateur** [comment]
It's a defined behavior set by rocket:

https://github.com/SergioBenitez/Rocket/blob/f64029f079882c1fe8e47d65d4a57ec260729bea/CHANGELOG.md?#L857

https://github.com/SergioBenitez/Rocket/blob/13732f8a6b273b2987fb021c0c58e81b179c60a7/core/lib/src/log.rs#L181-L183

Rocket doesn't provide a way to specify this behavior, I suggest you bring this issue in rocket repository.

**Comment by Canop** [comment]
> Rocket doesn't provide a way to specify this behavior, I suggest you bring this issue in rocket repository.

Yes. Most applications testing whether they run in a TTY terminal also provide a launch argument to bypass the test, like `--color=true`.

**Comment by Canop** [comment]
Reopening because I need to update the documentation to help users deal with this problem (when the running application has the relevant capabilities).

As an example, here's what run does with [lfs](https://github.com/Canop/lfs) and no specific configuration:

![image](https://user-images.githubusercontent.com/617006/192241766-84665ed6-4937-4afc-9eba-c32f80baf273.png)

If I change the bacon.toml run job like this:

```
[jobs.run]
command = ["cargo", "run", "--color", "always", "--", "--color", "yes"]
need_stdout = true
allow_warnings = true
```

Then I get this:

![image](https://user-images.githubusercontent.com/617006/192242033-4862fd8d-ed26-4928-9ace-764e2e05ce2c.png)

**Comment by Stargateur** [comment]
I didn't test but tool like https://lib.rs/crates/faketty or https://lib.rs/crates/fake-tty (I picked Rust solution but other way exist) could be use as an user of bacon to have a dirty way to override such behavior, `faketty cargo run` in bacon could work.

**Comment by Canop** [comment]
@Stargateur This is interesting but it can't be a bacon default as you don't always want the full craziness of  TTY (like animations)

**Comment by Canop** [comment]
Added an advice in the cookbook: https://dystroy.org/bacon/cookbook/#run-binaries-and-examples

**Comment by Stargateur** [comment]
I mean this as a user custom job, but if you see a good way to integrate this to bacon why not. Thus I think it's a bad idea cause this remove the responsibility of end app that should have a color always option or something similar.
